# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmWFa5DeuiZPM-GfFfn_i10EnfHQGlRa
"""

def purchase(price, tax):
    tax = price * 0.1
    total = price + tax
    return total

prices = purchase(1000, 10)
print(f"{prices}円")

