# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmWFa5DeuiZPM-GfFfn_i10EnfHQGlRa
"""

tax = 1.1
def total():

    price1 = 100
    price2 = 200

    return price1 + price2

print (total() * tax)

