# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmWFa5DeuiZPM-GfFfn_i10EnfHQGlRa
"""

array = ["水","金","地","火","木","土","天","海","冥"]

for i in array:
    print(i)


num = 0
while num < 9:
    print(array[num])
    num += 1